"""create core tables

Revision ID: 9e27c568112e
Revises:
Create Date: 2026-08-30 19:30:56.443268
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9e27c568112e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="knowledge_base_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("vector_collection_name", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "embedding_dimension > 0", name=op.f("ck_knowledge_bases_embedding_dimension_positive")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')",
            name=op.f("ck_knowledge_bases_knowledge_base_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
        sa.UniqueConstraint(
            "vector_collection_name", name=op.f("uq_knowledge_bases_vector_collection_name")
        ),
    )
    op.create_table(
        "documents",
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "markdown",
                "web_page",
                "pdf",
                "plain_text",
                name="document_source_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "failed",
                name="document_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("canonical_uri", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("cleaned_content", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('markdown', 'web_page', 'pdf', 'plain_text')",
            name=op.f("ck_documents_document_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed')",
            name=op.f("ck_documents_document_status"),
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_documents_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_documents_knowledge_base_id"), "documents", ["knowledge_base_id"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("vector_point_id", sa.Uuid(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "character_count >= 0", name=op.f("ck_chunks_character_count_nonnegative")
        ),
        sa.CheckConstraint(
            "sequence_index >= 0", name=op.f("ck_chunks_sequence_index_nonnegative")
        ),
        sa.CheckConstraint(
            "start_offset IS NULL OR end_offset IS NULL OR start_offset <= end_offset",
            name=op.f("ck_chunks_offset_order"),
        ),
        sa.CheckConstraint(
            "token_count IS NULL OR token_count >= 0",
            name=op.f("ck_chunks_token_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "sequence_index", name="uq_chunks_document_sequence"),
        sa.UniqueConstraint("vector_point_id", name=op.f("uq_chunks_vector_point_id")),
    )
    op.create_index(op.f("ix_chunks_content_hash"), "chunks", ["content_hash"], unique=False)
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    op.create_table(
        "ingestion_tasks",
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum(
                "ingest_document",
                "reindex_document",
                "export_knowledge_base",
                name="ingestion_task_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "crawling",
                "parsing",
                "chunking",
                "embedding",
                "indexing",
                "retrying",
                "completed",
                "failed",
                "cancelled",
                "partially_completed",
                name="ingestion_task_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_stage", sa.String(length=80), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_ingestion_tasks_progress_percentage")
        ),
        sa.CheckConstraint(
            "task_type IN ('ingest_document', 'reindex_document', 'export_knowledge_base')",
            name=op.f("ck_ingestion_tasks_ingestion_task_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'crawling', 'parsing', 'chunking', 'embedding', "
            "'indexing', 'retrying', 'completed', 'failed', 'cancelled', "
            "'partially_completed')",
            name=op.f("ck_ingestion_tasks_ingestion_task_status"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_ingestion_tasks_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_ingestion_tasks_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_tasks")),
        sa.UniqueConstraint("celery_task_id", name=op.f("uq_ingestion_tasks_celery_task_id")),
    )
    op.create_index(
        op.f("ix_ingestion_tasks_document_id"), "ingestion_tasks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_tasks_knowledge_base_id"),
        "ingestion_tasks",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ingestion_tasks_status"), "ingestion_tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_tasks_status"), table_name="ingestion_tasks")
    op.drop_index(op.f("ix_ingestion_tasks_knowledge_base_id"), table_name="ingestion_tasks")
    op.drop_index(op.f("ix_ingestion_tasks_document_id"), table_name="ingestion_tasks")
    op.drop_table("ingestion_tasks")
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_content_hash"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_documents_knowledge_base_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###
